### ISSUE TITLE
Sorry, but your link (https://mp.weixin.qq.com/s/xxxxxx) is broken, restricted, or content is empty

### ISSUE THREAD

**Issue by wensley** [albertincx/formatbot1#13]
```
InstantViewBot  | availableOne true
InstantViewBot  | elTime 223
InstantViewBot  | 223s, 214ms test1DEV
InstantViewBot  | queue job undefined
InstantViewBot  | reset start2
InstantViewBot  | merc
InstantViewBot  | before san 349
InstantViewBot  | length 70
InstantViewBot  | domed 126
InstantViewBot  | Error: empty ivlink
InstantViewBot  |     at Object.makeIvLink (/app/src/api/utils/ivMaker.js:45:11)
InstantViewBot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
InstantViewBot  |     at async jobMessage (/app/src/api/routes/format/index.js:434:11)
InstantViewBot  | error = broken https://mp.weixin.qq.com/s/xxxxxxx Error: empty ivlink
```
how to fix it?
Thanks!

**Comment by albertincx** [comment]
For a link to work, you need 2 things.
1 The site can downloaded by the wget command (linux)
2 The site has a modern HTML layout
